// Date: 3/19/2015 4:46:22 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.steveuniverse.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class amethyst_model extends ModelBase
{
  //fields
    ModelRenderer hair_1;
    ModelRenderer hair_2;
    ModelRenderer hair_3;
    ModelRenderer hair_4;
    ModelRenderer hair_5;
    ModelRenderer hair_6;
    ModelRenderer hair_7;
    ModelRenderer hair_8;
    ModelRenderer hair_9;
    ModelRenderer hair_10;
    ModelRenderer hair_11;
    ModelRenderer hair_12;
    ModelRenderer hair_13;
    ModelRenderer hair_14;
    ModelRenderer head;
    ModelRenderer nose;
    ModelRenderer neck;
    ModelRenderer body;
    ModelRenderer chest;
    ModelRenderer right_top_arm;
    ModelRenderer right_middle_arm;
    ModelRenderer right_lower_arm;
    ModelRenderer right_hand;
    ModelRenderer left_arm_top;
    ModelRenderer left_arm_middle;
    ModelRenderer left_arm_lower;
    ModelRenderer left_hand;
    ModelRenderer waist_1;
    ModelRenderer waist_2;
    ModelRenderer waist_3;
    ModelRenderer right_upper_leg;
    ModelRenderer right_lower_leg;
    ModelRenderer right_foot;
    ModelRenderer left_upper_leg;
    ModelRenderer left_lower_leg;
    ModelRenderer left_foot;
  
  public amethyst_model()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      hair_1 = new ModelRenderer(this, 56, 32);
      hair_1.addBox(-7F, 0F, -3F, 14, 2, 6);
      hair_1.setRotationPoint(-1F, -15F, 0F);
      hair_1.setTextureSize(128, 128);
      hair_1.mirror = true;
      setRotation(hair_1, 0F, 0F, 0F);
      hair_2 = new ModelRenderer(this, 26, 44);
      hair_2.addBox(0F, 0F, 0F, 3, 8, 6);
      hair_2.setRotationPoint(4F, -14F, -2F);
      hair_2.setTextureSize(128, 128);
      hair_2.mirror = true;
      setRotation(hair_2, 0F, 0F, 0F);
      hair_3 = new ModelRenderer(this, 16, 30);
      hair_3.addBox(-7F, -12F, 0F, 16, 26, 3);
      hair_3.setRotationPoint(-2F, 6F, 1F);
      hair_3.setTextureSize(128, 128);
      hair_3.mirror = true;
      setRotation(hair_3, 0F, 0F, 0F);
      hair_4 = new ModelRenderer(this, 56, 24);
      hair_4.addBox(0F, 0F, 0F, 7, 3, 3);
      hair_4.setRotationPoint(-1F, -14.8F, -5F);
      hair_4.setTextureSize(128, 128);
      hair_4.mirror = true;
      setRotation(hair_4, 0F, 0F, 0F);
      hair_5 = new ModelRenderer(this, 77, 19);
      hair_5.addBox(-3F, 0F, 0F, 6, 8, 3);
      hair_5.setRotationPoint(1.6F, -13.3F, -5F);
      hair_5.setTextureSize(128, 128);
      hair_5.mirror = true;
      setRotation(hair_5, 0F, 0F, -0.5205006F);
      hair_6 = new ModelRenderer(this, 36, 16);
      hair_6.addBox(0F, 0F, 0F, 3, 6, 6);
      hair_6.setRotationPoint(-9F, -14F, -2F);
      hair_6.setTextureSize(128, 128);
      hair_6.mirror = true;
      setRotation(hair_6, 0F, 0F, 0F);
      hair_7 = new ModelRenderer(this, 15, 18);
      hair_7.addBox(0F, 0F, -4F, 3, 2, 7);
      hair_7.setRotationPoint(-9F, -8F, 1F);
      hair_7.setTextureSize(128, 128);
      hair_7.mirror = true;
      setRotation(hair_7, 0F, 0F, 0F);
      hair_8 = new ModelRenderer(this, 16, 11);
      hair_8.addBox(0F, 0F, 0F, 6, 2, 3);
      hair_8.setRotationPoint(-15F, -8F, 1F);
      hair_8.setTextureSize(128, 128);
      hair_8.mirror = true;
      setRotation(hair_8, 0F, 0F, 0F);
      hair_9 = new ModelRenderer(this, 20, 4);
      hair_9.addBox(0F, 0F, 0F, 2, 2, 3);
      hair_9.setRotationPoint(7F, -5F, 1F);
      hair_9.setTextureSize(128, 128);
      hair_9.mirror = true;
      setRotation(hair_9, 0F, 0F, 0F);
      hair_10 = new ModelRenderer(this, 37, 8);
      hair_10.addBox(0F, 0F, 0F, 5, 3, 3);
      hair_10.setRotationPoint(7F, -3F, 1F);
      hair_10.setTextureSize(128, 128);
      hair_10.mirror = true;
      setRotation(hair_10, 0F, 0F, 0F);
      hair_11 = new ModelRenderer(this, 58, 15);
      hair_11.addBox(0F, 0F, 0F, 5, 3, 3);
      hair_11.setRotationPoint(-14F, -6F, 1F);
      hair_11.setTextureSize(128, 128);
      hair_11.mirror = true;
      setRotation(hair_11, 0F, 0F, 0F);
      hair_12 = new ModelRenderer(this, 59, 8);
      hair_12.addBox(0F, 0F, 0F, 3, 2, 3);
      hair_12.setRotationPoint(7F, 0F, 1F);
      hair_12.setTextureSize(128, 128);
      hair_12.mirror = true;
      setRotation(hair_12, 0F, 0F, 0F);
      hair_13 = new ModelRenderer(this, 81, 12);
      hair_13.addBox(0F, 0F, 0F, 2, 2, 3);
      hair_13.setRotationPoint(-11F, -10F, 1F);
      hair_13.setTextureSize(128, 128);
      hair_13.mirror = true;
      setRotation(hair_13, 0F, 0F, 0F);
      hair_14 = new ModelRenderer(this, 80, 5);
      hair_14.addBox(0F, 0F, 0F, 3, 2, 3);
      hair_14.setRotationPoint(-12F, -3F, 1F);
      hair_14.setTextureSize(128, 128);
      hair_14.mirror = true;
      setRotation(hair_14, 0F, 0F, 0F);
      head = new ModelRenderer(this, 58, 42);
      head.addBox(-5F, -7F, 0F, 10, 8, 8);
      head.setRotationPoint(-1F, -7F, -4F);
      head.setTextureSize(128, 128);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      nose = new ModelRenderer(this, 95, 49);
      nose.addBox(-1F, 0F, 0F, 2, 1, 1);
      nose.setRotationPoint(-1F, -10F, -5F);
      nose.setTextureSize(128, 128);
      nose.mirror = true;
      setRotation(nose, 0F, 0F, 0F);
      neck = new ModelRenderer(this, 70, 60);
      neck.addBox(-1F, 0F, 0F, 3, 2, 2);
      neck.setRotationPoint(-1.5F, -6F, -2F);
      neck.setTextureSize(128, 128);
      neck.mirror = true;
      setRotation(neck, 0F, 0F, 0F);
      body = new ModelRenderer(this, 46, 66);
      body.addBox(-6F, 0F, 0F, 12, 7, 5);
      body.setRotationPoint(-1F, -4F, -4F);
      body.setTextureSize(128, 128);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      chest = new ModelRenderer(this, 81, 66);
      chest.addBox(-4F, -2F, 0F, 8, 5, 2);
      chest.setRotationPoint(-1F, -1F, -6F);
      chest.setTextureSize(128, 128);
      chest.mirror = true;
      setRotation(chest, 0F, 0F, 0F);
      right_top_arm = new ModelRenderer(this, 110, 70);
      right_top_arm.addBox(-2F, 0F, 0F, 4, 3, 4);
      right_top_arm.setRotationPoint(7.5F, -2F, -3F);
      right_top_arm.setTextureSize(128, 128);
      right_top_arm.mirror = true;
      setRotation(right_top_arm, 0F, 0F, 1.59868F);
      right_middle_arm = new ModelRenderer(this, 110, 79);
      right_middle_arm.addBox(-2F, 0F, 0F, 4, 6, 4);
      right_middle_arm.setRotationPoint(5.8F, -3.1F, -3F);
      right_middle_arm.setTextureSize(128, 128);
      right_middle_arm.mirror = true;
      setRotation(right_middle_arm, 0F, 0F, -0.475783F);
      right_lower_arm = new ModelRenderer(this, 110, 91);
      right_lower_arm.addBox(-2F, 0F, 0F, 4, 6, 4);
      right_lower_arm.setRotationPoint(8.5F, 2.2F, -3F);
      right_lower_arm.setTextureSize(128, 128);
      right_lower_arm.mirror = true;
      setRotation(right_lower_arm, 0F, 0F, -0.4644228F);
      right_hand = new ModelRenderer(this, 107, 103);
      right_hand.addBox(0F, 0F, 0F, 5, 4, 5);
      right_hand.setRotationPoint(8F, 7F, -3.5F);
      right_hand.setTextureSize(128, 128);
      right_hand.mirror = true;
      setRotation(right_hand, 0F, 0F, -0.0743572F);
      left_arm_top = new ModelRenderer(this, 26, 73);
      left_arm_top.addBox(-2F, 0F, 0F, 4, 3, 4);
      left_arm_top.setRotationPoint(-6.5F, -2F, -3F);
      left_arm_top.setTextureSize(128, 128);
      left_arm_top.mirror = true;
      setRotation(left_arm_top, 0F, 0F, 1.59868F);
      left_arm_middle = new ModelRenderer(this, 26, 82);
      left_arm_middle.addBox(-2F, 0F, 0F, 4, 6, 4);
      left_arm_middle.setRotationPoint(-7.7F, -3.1F, -3F);
      left_arm_middle.setTextureSize(128, 128);
      left_arm_middle.mirror = true;
      setRotation(left_arm_middle, 0F, 0F, 0.5022211F);
      left_arm_lower = new ModelRenderer(this, 26, 94);
      left_arm_lower.addBox(-2F, 0F, 0F, 4, 6, 4);
      left_arm_lower.setRotationPoint(-10.5F, 2.1F, -3F);
      left_arm_lower.setTextureSize(128, 128);
      left_arm_lower.mirror = true;
      setRotation(left_arm_lower, 0F, 0F, 0.4969541F);
      left_hand = new ModelRenderer(this, 25, 106);
      left_hand.addBox(0F, 0F, 0F, 5, 4, 5);
      left_hand.setRotationPoint(-15.1F, 6.4F, -3.5F);
      left_hand.setTextureSize(128, 128);
      left_hand.mirror = true;
      setRotation(left_hand, 0F, 0F, 0.0303625F);
      waist_1 = new ModelRenderer(this, 84, 80);
      waist_1.addBox(-3F, 0F, 0F, 6, 7, 5);
      waist_1.setRotationPoint(3F, 3F, -4F);
      waist_1.setTextureSize(128, 128);
      waist_1.mirror = true;
      setRotation(waist_1, 0F, 0F, 0F);
      waist_2 = new ModelRenderer(this, 69, 80);
      waist_2.addBox(0F, 0F, 0F, 2, 7, 5);
      waist_2.setRotationPoint(-2F, 3F, -4F);
      waist_2.setTextureSize(128, 128);
      waist_2.mirror = true;
      setRotation(waist_2, 0F, 0F, 0F);
      waist_3 = new ModelRenderer(this, 46, 80);
      waist_3.addBox(-3F, 0F, 0F, 6, 7, 5);
      waist_3.setRotationPoint(-5F, 3F, -4F);
      waist_3.setTextureSize(128, 128);
      waist_3.mirror = true;
      setRotation(waist_3, 0F, 0F, 0F);
      right_upper_leg = new ModelRenderer(this, 84, 94);
      right_upper_leg.addBox(0F, 0F, 0F, 6, 7, 5);
      right_upper_leg.setRotationPoint(0F, 10F, -4F);
      right_upper_leg.setTextureSize(128, 128);
      right_upper_leg.mirror = true;
      setRotation(right_upper_leg, 0F, 0F, 0F);
      right_lower_leg = new ModelRenderer(this, 85, 108);
      right_lower_leg.addBox(0F, 0F, 0F, 6, 4, 4);
      right_lower_leg.setRotationPoint(0F, 17F, -4F);
      right_lower_leg.setTextureSize(128, 128);
      right_lower_leg.mirror = true;
      setRotation(right_lower_leg, 0F, 0F, 0F);
      right_foot = new ModelRenderer(this, 83, 118);
      right_foot.addBox(0F, 0F, 0F, 6, 3, 6);
      right_foot.setRotationPoint(0F, 21F, -6F);
      right_foot.setTextureSize(128, 128);
      right_foot.mirror = true;
      setRotation(right_foot, 0F, 0F, 0F);
      left_upper_leg = new ModelRenderer(this, 46, 94);
      left_upper_leg.addBox(0F, 0F, 0F, 6, 7, 5);
      left_upper_leg.setRotationPoint(-8F, 10F, -4F);
      left_upper_leg.setTextureSize(128, 128);
      left_upper_leg.mirror = true;
      setRotation(left_upper_leg, 0F, 0F, 0F);
      left_lower_leg = new ModelRenderer(this, 46, 108);
      left_lower_leg.addBox(0F, 0F, 0F, 6, 4, 4);
      left_lower_leg.setRotationPoint(-8F, 17F, -4F);
      left_lower_leg.setTextureSize(128, 128);
      left_lower_leg.mirror = true;
      setRotation(left_lower_leg, 0F, 0F, 0F);
      left_foot = new ModelRenderer(this, 46, 118);
      left_foot.addBox(0F, 0F, 0F, 6, 3, 6);
      left_foot.setRotationPoint(-8F, 21F, -6F);
      left_foot.setTextureSize(128, 128);
      left_foot.mirror = true;
      setRotation(left_foot, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    hair_1.render(f5);
    hair_2.render(f5);
    hair_3.render(f5);
    hair_4.render(f5);
    hair_5.render(f5);
    hair_6.render(f5);
    hair_7.render(f5);
    hair_8.render(f5);
    hair_9.render(f5);
    hair_10.render(f5);
    hair_11.render(f5);
    hair_12.render(f5);
    hair_13.render(f5);
    hair_14.render(f5);
    head.render(f5);
    nose.render(f5);
    neck.render(f5);
    body.render(f5);
    chest.render(f5);
    right_top_arm.render(f5);
    right_middle_arm.render(f5);
    right_lower_arm.render(f5);
    right_hand.render(f5);
    left_arm_top.render(f5);
    left_arm_middle.render(f5);
    left_arm_lower.render(f5);
    left_hand.render(f5);
    waist_1.render(f5);
    waist_2.render(f5);
    waist_3.render(f5);
    right_upper_leg.render(f5);
    right_lower_leg.render(f5);
    right_foot.render(f5);
    left_upper_leg.render(f5);
    left_lower_leg.render(f5);
    left_foot.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
