package com.steveuniverse.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class pearl_model extends ModelBase
{
	  //fields
	    ModelRenderer Leg1;
	    ModelRenderer Waist;
	    ModelRenderer Leg2;
	    ModelRenderer Foot2;
	    ModelRenderer Foot1;
	    ModelRenderer SkirtBottom;
	    ModelRenderer SkirtTop;
	    ModelRenderer Torso;
	    ModelRenderer Chest;
	    ModelRenderer Toe1;
	    ModelRenderer Toe2;
	    ModelRenderer FootAngle2;
	    ModelRenderer FootAngle1;
	    ModelRenderer Neck;
	    ModelRenderer FootLining1;
	    ModelRenderer Head;
	    ModelRenderer Eye2;
	    ModelRenderer Eye1;
	    ModelRenderer Pupil1;
	    ModelRenderer Mouth;
	    ModelRenderer Pupil2;
	    ModelRenderer HairBitTop1;
	    ModelRenderer Nose;
	    ModelRenderer HairBitBottom1;
	    ModelRenderer HairBitTop2;
	    ModelRenderer HairBitBottom2;
	    ModelRenderer FootLining2;
	    ModelRenderer HairBackTop;
	    ModelRenderer HairBackBottom;
	    ModelRenderer HairBackMid;
	    ModelRenderer Arm1;
	    ModelRenderer Arm2;
	    ModelRenderer Gem;
	  
	  public pearl_model()
	  {
	    textureWidth = 512;
	    textureHeight = 512;
	    
	      Leg1 = new ModelRenderer(this, 100, 115);
	      Leg1.addBox(0F, 0F, 0F, 2, 14, 2);
	      Leg1.setRotationPoint(-3F, 9F, 0F);
	      Leg1.setTextureSize(512, 512);
	      Leg1.mirror = true;
	      setRotation(Leg1, 0F, 0F, 0F);
	      Waist = new ModelRenderer(this, 100, 101);
	      Waist.addBox(0F, 0F, 0F, 6, 3, 2);
	      Waist.setRotationPoint(-3F, 6F, 0F);
	      Waist.setTextureSize(512, 512);
	      Waist.mirror = true;
	      setRotation(Waist, 0F, 0F, 0F);
	      Leg2 = new ModelRenderer(this, 100, 115);
	      Leg2.addBox(0F, 0F, 0F, 2, 14, 2);
	      Leg2.setRotationPoint(1F, 9F, 0F);
	      Leg2.setTextureSize(512, 512);
	      Leg2.mirror = true;
	      setRotation(Leg2, 0F, 0F, 0F);
	      Foot2 = new ModelRenderer(this, 100, 155);
	      Foot2.addBox(0F, 0F, 0F, 2, 1, 6);
	      Foot2.setRotationPoint(1F, 23F, -4F);
	      Foot2.setTextureSize(512, 512);
	      Foot2.mirror = true;
	      setRotation(Foot2, 0F, 0F, 0F);
	      Foot1 = new ModelRenderer(this, 100, 155);
	      Foot1.addBox(0F, 0F, 0F, 2, 1, 6);
	      Foot1.setRotationPoint(-3F, 23F, -4F);
	      Foot1.setTextureSize(512, 512);
	      Foot1.mirror = true;
	      setRotation(Foot1, 0F, 0F, 0F);
	      SkirtBottom = new ModelRenderer(this, 100, 86);
	      SkirtBottom.addBox(0F, 0F, 0F, 8, 1, 4);
	      SkirtBottom.setRotationPoint(-4F, 6F, -1F);
	      SkirtBottom.setTextureSize(512, 512);
	      SkirtBottom.mirror = true;
	      setRotation(SkirtBottom, 0F, 0F, 0F);
	      SkirtTop = new ModelRenderer(this, 100, 75);
	      SkirtTop.addBox(0F, 0F, 0F, 7, 1, 3);
	      SkirtTop.setRotationPoint(-3.5F, 5.5F, -0.5F);
	      SkirtTop.setTextureSize(512, 512);
	      SkirtTop.mirror = true;
	      setRotation(SkirtTop, 0F, 0F, 0F);
	      Torso = new ModelRenderer(this, 100, 57);
	      Torso.addBox(0F, 0F, 0F, 6, 8, 2);
	      Torso.setRotationPoint(-3F, -2.5F, 0F);
	      Torso.setTextureSize(512, 512);
	      Torso.mirror = true;
	      setRotation(Torso, 0F, 0F, 0F);
	      Chest = new ModelRenderer(this, 100, 41);
	      Chest.addBox(0F, 0F, 0F, 6, 4, 1);
	      Chest.setRotationPoint(-3F, -1.5F, -0.5F);
	      Chest.setTextureSize(512, 512);
	      Chest.mirror = true;
	      setRotation(Chest, 0F, 0F, 0F);
	      Toe1 = new ModelRenderer(this, 100, 169);
	      Toe1.addBox(0F, 0F, 0F, 1, 1, 1);
	      Toe1.setRotationPoint(-2.5F, 23F, -5F);
	      Toe1.setTextureSize(512, 512);
	      Toe1.mirror = true;
	      setRotation(Toe1, 0F, 0F, 0F);
	      Toe2 = new ModelRenderer(this, 100, 169);
	      Toe2.addBox(0F, 0F, 0F, 1, 1, 1);
	      Toe2.setRotationPoint(1.5F, 23F, -5F);
	      Toe2.setTextureSize(512, 512);
	      Toe2.mirror = true;
	      setRotation(Toe2, 0F, 0F, 0F);
	      FootAngle2 = new ModelRenderer(this, 100, 145);
	      FootAngle2.addBox(0F, 0F, 0F, 2, 1, 3);
	      FootAngle2.setRotationPoint(1F, 23F, -3F);
	      FootAngle2.setTextureSize(512, 512);
	      FootAngle2.mirror = true;
	      setRotation(FootAngle2, 0.1047198F, 0F, 0F);
	      FootAngle1 = new ModelRenderer(this, 100, 145);
	      FootAngle1.addBox(0F, 0F, 0F, 2, 1, 3);
	      FootAngle1.setRotationPoint(-3F, 23F, -3F);
	      FootAngle1.setTextureSize(512, 512);
	      FootAngle1.mirror = true;
	      setRotation(FootAngle1, 0.1047198F, 0F, 0F);
	      Neck = new ModelRenderer(this, 100, 26);
	      Neck.addBox(0F, 0F, 0F, 1, 3, 1);
	      Neck.setRotationPoint(-0.5F, -5F, 0.5F);
	      Neck.setTextureSize(512, 512);
	      Neck.mirror = true;
	      setRotation(Neck, 0F, 0F, 0F);
	      FootLining1 = new ModelRenderer(this, 114, 147);
	      FootLining1.addBox(0F, 0F, 0F, 1, 1, 3);
	      FootLining1.setRotationPoint(-2.5F, 23F, -4F);
	      FootLining1.setTextureSize(512, 512);
	      FootLining1.mirror = true;
	      setRotation(FootLining1, 0.1047198F, 0F, 0F);
	      Head = new ModelRenderer(this, 100, 9);
	      Head.addBox(0F, 0F, 0F, 6, 7, 4);
	      Head.setRotationPoint(-3F, -12F, -1F);
	      Head.setTextureSize(512, 512);
	      Head.mirror = true;
	      setRotation(Head, 0F, 0F, 0F);
	      Eye2 = new ModelRenderer(this, 78, 15);
	      Eye2.addBox(0F, 0F, 0F, 2, 2, 1);
	      Eye2.setRotationPoint(0.7F, -9.6F, -1.1F);
	      Eye2.setTextureSize(512, 512);
	      Eye2.mirror = true;
	      setRotation(Eye2, 0F, 0F, 0F);
	      Eye1 = new ModelRenderer(this, 78, 15);
	      Eye1.addBox(0F, 0F, 0F, 2, 2, 1);
	      Eye1.setRotationPoint(-2.7F, -9.6F, -1.05F);
	      Eye1.setTextureSize(512, 512);
	      Eye1.mirror = true;
	      setRotation(Eye1, 0F, 0F, 0F);
	      Pupil1 = new ModelRenderer(this, 78, 52);
	      Pupil1.addBox(0F, 0F, 0F, 1, 2, 1);
	      Pupil1.setRotationPoint(-2F, -9.6F, -1.1F);
	      Pupil1.setTextureSize(512, 512);
	      Pupil1.mirror = true;
	      setRotation(Pupil1, 0F, 0F, 0F);
	      Mouth = new ModelRenderer(this, 77, 43);
	      Mouth.addBox(0F, 0F, 0F, 3, 1, 1);
	      Mouth.setRotationPoint(-1.5F, -6.4F, -1.05F);
	      Mouth.setTextureSize(512, 512);
	      Mouth.mirror = true;
	      setRotation(Mouth, 0.7853982F, 0F, 0F);
	      Pupil2 = new ModelRenderer(this, 78, 52);
	      Pupil2.addBox(0F, 0F, 0F, 1, 2, 1);
	      Pupil2.setRotationPoint(1F, -9.6F, -1.15F);
	      Pupil2.setTextureSize(512, 512);
	      Pupil2.mirror = true;
	      setRotation(Pupil2, 0F, 0F, 0F);
	      HairBitTop1 = new ModelRenderer(this, 56, 35);
	      HairBitTop1.addBox(0F, 0F, 0F, 1, 1, 1);
	      HairBitTop1.setRotationPoint(-3.1F, -10.8F, -1.1F);
	      HairBitTop1.setTextureSize(512, 512);
	      HairBitTop1.mirror = true;
	      setRotation(HairBitTop1, 0F, 0F, 0F);
	      Nose = new ModelRenderer(this, 75, 41);
	      Nose.addBox(0F, 0F, 0F, 1, 1, 2);
	      Nose.setRotationPoint(-0.5F, -8F, -2.9F);
	      Nose.setTextureSize(512, 512);
	      Nose.mirror = true;
	      setRotation(Nose, -0.0698132F, 0F, 0F);
	      HairBitBottom1 = new ModelRenderer(this, 56, 35);
	      HairBitBottom1.addBox(0F, 0F, 0F, 1, 1, 1);
	      HairBitBottom1.setRotationPoint(-3.1F, -6.9F, -0.9F);
	      HairBitBottom1.setTextureSize(512, 512);
	      HairBitBottom1.mirror = true;
	      setRotation(HairBitBottom1, 0F, 0F, 0F);
	      HairBitTop2 = new ModelRenderer(this, 56, 35);
	      HairBitTop2.addBox(0F, 0F, 0F, 1, 1, 1);
	      HairBitTop2.setRotationPoint(2.1F, -10.8F, -1.1F);
	      HairBitTop2.setTextureSize(512, 512);
	      HairBitTop2.mirror = true;
	      setRotation(HairBitTop2, 0F, 0F, 0F);
	      HairBitBottom2 = new ModelRenderer(this, 56, 35);
	      HairBitBottom2.addBox(0F, 0F, 0F, 1, 1, 1);
	      HairBitBottom2.setRotationPoint(2.1F, -6.9F, -0.9F);
	      HairBitBottom2.setTextureSize(512, 512);
	      HairBitBottom2.mirror = true;
	      setRotation(HairBitBottom2, 0F, 0F, 0F);
	      FootLining2 = new ModelRenderer(this, 114, 147);
	      FootLining2.addBox(0F, 0F, 0F, 1, 1, 3);
	      FootLining2.setRotationPoint(1.5F, 23F, -4F);
	      FootLining2.setTextureSize(512, 512);
	      FootLining2.mirror = true;
	      setRotation(FootLining2, 0.1047198F, 0F, 0F);
	      HairBackTop = new ModelRenderer(this, 53, 22);
	      HairBackTop.addBox(0F, 0F, 0F, 6, 6, 2);
	      HairBackTop.setRotationPoint(-3F, -10.1F, 2F);
	      HairBackTop.setTextureSize(512, 512);
	      HairBackTop.mirror = true;
	      setRotation(HairBackTop, 1.134464F, 0F, 0F);
	      HairBackBottom = new ModelRenderer(this, 53, 22);
	      HairBackBottom.addBox(0F, 0F, 0F, 6, 6, 2);
	      HairBackBottom.setRotationPoint(-3F, -9.5F, 7.5F);
	      HairBackBottom.setTextureSize(512, 512);
	      HairBackBottom.mirror = true;
	      setRotation(HairBackBottom, -1.134464F, 0F, 0F);
	      HairBackMid = new ModelRenderer(this, 54, 19);
	      HairBackMid.addBox(0F, 0F, 0F, 6, 3, 3);
	      HairBackMid.setRotationPoint(-3F, -10F, 3F);
	      HairBackMid.setTextureSize(512, 512);
	      HairBackMid.mirror = true;
	      setRotation(HairBackMid, 0F, 0F, 0F);
	      Arm1 = new ModelRenderer(this, 72, 34);
	      Arm1.addBox(0F, 0F, 0F, 2, 14, 2);
	      Arm1.setRotationPoint(-4.9F, -2F, 0F);
	      Arm1.setTextureSize(512, 512);
	      Arm1.mirror = true;
	      setRotation(Arm1, 0F, 0F, 0.1396263F);
	      Arm2 = new ModelRenderer(this, 72, 34);
	      Arm2.addBox(3.1F, -1.3F, 0F, 2, 14, 2);
	      Arm2.setRotationPoint(0F, 0F, 0F);
	      Arm2.setTextureSize(512, 512);
	      Arm2.mirror = true;
	      setRotation(Arm2, 0F, 0F, -0.1396263F);
	      Gem = new ModelRenderer(this, 61, 10);
	      Gem.addBox(0F, 0F, 0F, 2, 2, 1);
	      Gem.setRotationPoint(-1F, -11.7F, -1.2F);
	      Gem.setTextureSize(512, 512);
	      Gem.mirror = true;
	      setRotation(Gem, 0F, 0F, 0F);
	  }
	  
	  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	  {
	    super.render(entity, f, f1, f2, f3, f4, f5);
	    setRotationAngles(f, f1, f2, f3, f4, f5);
	    Leg1.render(f5);
	    Waist.render(f5);
	    Leg2.render(f5);
	    Foot2.render(f5);
	    Foot1.render(f5);
	    SkirtBottom.render(f5);
	    SkirtTop.render(f5);
	    Torso.render(f5);
	    Chest.render(f5);
	    Toe1.render(f5);
	    Toe2.render(f5);
	    FootAngle2.render(f5);
	    FootAngle1.render(f5);
	    Neck.render(f5);
	    FootLining1.render(f5);
	    Head.render(f5);
	    Eye2.render(f5);
	    Eye1.render(f5);
	    Pupil1.render(f5);
	    Mouth.render(f5);
	    Pupil2.render(f5);
	    HairBitTop1.render(f5);
	    Nose.render(f5);
	    HairBitBottom1.render(f5);
	    HairBitTop2.render(f5);
	    HairBitBottom2.render(f5);
	    FootLining2.render(f5);
	    HairBackTop.render(f5);
	    HairBackBottom.render(f5);
	    HairBackMid.render(f5);
	    Arm1.render(f5);
	    Arm2.render(f5);
	    Gem.render(f5);
	  }
	  
	  private void setRotation(ModelRenderer model, float x, float y, float z)
	  {
	    model.rotateAngleX = x;
	    model.rotateAngleY = y;
	    model.rotateAngleZ = z;
	  }
	  
	  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	  {
	    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
	  }

	}
