package com.steveuniverse.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class peridot_model extends ModelBase
{
	  //fields
	    ModelRenderer Head;
	    ModelRenderer GlassesBottom1;
	    ModelRenderer GlassesTop;
	    ModelRenderer GlassesBottom2;
	    ModelRenderer Eye1;
	    ModelRenderer Pupil1;
	    ModelRenderer Neck;
	    ModelRenderer GemTop;
	    ModelRenderer GemBottom;
	    ModelRenderer Eye2;
	    ModelRenderer Pupil2;
	    ModelRenderer Torso;
	    ModelRenderer Diamond1;
	    ModelRenderer TorsoBottom;
	    ModelRenderer Waist;
	    ModelRenderer Hair;
	    ModelRenderer Arm1;
	    ModelRenderer ThighTop;
	    ModelRenderer ShoulderCover1;
	    ModelRenderer ThighBottom;
	    ModelRenderer Boot1;
	    ModelRenderer Toe1;
	    ModelRenderer Leg1;
	    ModelRenderer Diamond2;
	    ModelRenderer Leg2;
	    ModelRenderer Diamond3;
	    ModelRenderer Boot2;
	    ModelRenderer Toe2;
	    ModelRenderer Glove1;
	    ModelRenderer Glove2;
	    ModelRenderer Arm2;
	    ModelRenderer ShoulderCover2;
	  
	  public peridot_model()
	  {
	    textureWidth = 256;
	    textureHeight = 256;
	    
	      Head = new ModelRenderer(this, 1, 1);
	      Head.addBox(0F, 0F, 0F, 6, 7, 4);
	      Head.setRotationPoint(-3F, -5F, -3F);
	      Head.setTextureSize(256, 256);
	      Head.mirror = true;
	      setRotation(Head, 0F, 0F, 0F);
	      GlassesBottom1 = new ModelRenderer(this, 30, 9);
	      GlassesBottom1.addBox(0F, 0F, 0F, 2, 2, 1);
	      GlassesBottom1.setRotationPoint(-3F, -1F, -3.05F);
	      GlassesBottom1.setTextureSize(256, 256);
	      GlassesBottom1.mirror = true;
	      setRotation(GlassesBottom1, 0F, 0F, -0.7853982F);
	      GlassesTop = new ModelRenderer(this, 24, 4);
	      GlassesTop.addBox(0F, 0F, 0F, 6, 4, 1);
	      GlassesTop.setRotationPoint(-3F, -5F, -3.05F);
	      GlassesTop.setTextureSize(256, 256);
	      GlassesTop.mirror = true;
	      setRotation(GlassesTop, 0F, 0F, 0F);
	      GlassesBottom2 = new ModelRenderer(this, 30, 9);
	      GlassesBottom2.addBox(0F, 0F, 0F, 2, 2, 1);
	      GlassesBottom2.setRotationPoint(0.1F, -1F, -3.05F);
	      GlassesBottom2.setTextureSize(256, 256);
	      GlassesBottom2.mirror = true;
	      setRotation(GlassesBottom2, 0F, 0F, -0.7853982F);
	      Eye1 = new ModelRenderer(this, 46, 3);
	      Eye1.addBox(0F, 0F, 0F, 2, 2, 1);
	      Eye1.setRotationPoint(-2.5F, -3F, -3.06F);
	      Eye1.setTextureSize(256, 256);
	      Eye1.mirror = true;
	      setRotation(Eye1, 0F, 0F, 0F);
	      Pupil1 = new ModelRenderer(this, 63, 6);
	      Pupil1.addBox(0F, 0F, 0F, 1, 1, 1);
	      Pupil1.setRotationPoint(-1.8F, -2.5F, -3.1F);
	      Pupil1.setTextureSize(256, 256);
	      Pupil1.mirror = true;
	      setRotation(Pupil1, 0F, 0F, 0F);
	      Neck = new ModelRenderer(this, 3, 2);
	      Neck.addBox(0F, 0F, 0F, 2, 2, 2);
	      Neck.setRotationPoint(-1F, 2F, -2F);
	      Neck.setTextureSize(256, 256);
	      Neck.mirror = true;
	      setRotation(Neck, 0F, 0F, 0F);
	      GemTop = new ModelRenderer(this, 65, 8);
	      GemTop.addBox(0F, 0F, 0F, 3, 1, 1);
	      GemTop.setRotationPoint(-1.5F, -4.5F, -3.2F);
	      GemTop.setTextureSize(256, 256);
	      GemTop.mirror = true;
	      setRotation(GemTop, 0F, 0F, 0F);
	      GemBottom = new ModelRenderer(this, 65, 8);
	      GemBottom.addBox(0F, 0F, 0F, 2, 1, 1);
	      GemBottom.setRotationPoint(-1F, -4F, -3.2F);
	      GemBottom.setTextureSize(256, 256);
	      GemBottom.mirror = true;
	      setRotation(GemBottom, 0F, 0F, 0F);
	      Eye2 = new ModelRenderer(this, 46, 3);
	      Eye2.addBox(0F, 0F, 0F, 2, 2, 1);
	      Eye2.setRotationPoint(0.5F, -3F, -3.06F);
	      Eye2.setTextureSize(256, 256);
	      Eye2.mirror = true;
	      setRotation(Eye2, 0F, 0F, 0F);
	      Pupil2 = new ModelRenderer(this, 66, 8);
	      Pupil2.addBox(0F, 0F, 0F, 1, 1, 1);
	      Pupil2.setRotationPoint(0.8F, -2.5F, -3.1F);
	      Pupil2.setTextureSize(256, 256);
	      Pupil2.mirror = true;
	      setRotation(Pupil2, 0F, 0F, 0F);
	      Torso = new ModelRenderer(this, 51, 37);
	      Torso.addBox(0F, 0F, 0F, 6, 4, 3);
	      Torso.setRotationPoint(-3F, 4F, -2.5F);
	      Torso.setTextureSize(256, 256);
	      Torso.mirror = true;
	      setRotation(Torso, 0F, 0F, 0F);
	      Diamond1 = new ModelRenderer(this, 86, 5);
	      Diamond1.addBox(0F, 0F, 0F, 2, 2, 1);
	      Diamond1.setRotationPoint(-1.4F, 7.5F, -3.2F);
	      Diamond1.setTextureSize(256, 256);
	      Diamond1.mirror = true;
	      setRotation(Diamond1, 0F, 0F, -0.7853982F);
	      TorsoBottom = new ModelRenderer(this, 97, 2);
	      TorsoBottom.addBox(0F, 0F, 0F, 5, 1, 3);
	      TorsoBottom.setRotationPoint(-2.5F, 8F, -2.5F);
	      TorsoBottom.setTextureSize(256, 256);
	      TorsoBottom.mirror = true;
	      setRotation(TorsoBottom, 0F, 0F, 0F);
	      Waist = new ModelRenderer(this, 126, 5);
	      Waist.addBox(0F, 0F, 0F, 3, 2, 3);
	      Waist.setRotationPoint(-1.5F, 9F, -2.5F);
	      Waist.setTextureSize(256, 256);
	      Waist.mirror = true;
	      setRotation(Waist, 0F, 0F, 0F);
	      Hair = new ModelRenderer(this, 96, 83);
	      Hair.addBox(0F, 0F, 0F, 12, 12, 5);
	      Hair.setRotationPoint(-8.5F, -3F, -2.95F);
	      Hair.setTextureSize(256, 256);
	      Hair.mirror = true;
	      setRotation(Hair, 0F, 0F, -0.7853982F);
	      Arm1 = new ModelRenderer(this, 5, 3);
	      Arm1.addBox(0F, 0F, 0F, 2, 7, 2);
	      Arm1.setRotationPoint(-5F, 4.5F, -2F);
	      Arm1.setTextureSize(256, 256);
	      Arm1.mirror = true;
	      setRotation(Arm1, 0F, 0F, 0.1396263F);
	      ThighTop = new ModelRenderer(this, 126, 5);
	      ThighTop.addBox(0F, 0F, 0F, 4, 1, 3);
	      ThighTop.setRotationPoint(-2F, 10.5F, -2.5F);
	      ThighTop.setTextureSize(256, 256);
	      ThighTop.mirror = true;
	      setRotation(ThighTop, 0F, 0F, 0F);
	      ShoulderCover1 = new ModelRenderer(this, 126, 5);
	      ShoulderCover1.addBox(0F, 0F, 0F, 2, 1, 3);
	      ShoulderCover1.setRotationPoint(-4F, 4F, -2.5F);
	      ShoulderCover1.setTextureSize(256, 256);
	      ShoulderCover1.mirror = true;
	      setRotation(ShoulderCover1, 0F, 0F, 0F);
	      ThighBottom = new ModelRenderer(this, 92, 34);
	      ThighBottom.addBox(0F, 0F, 0F, 5, 2, 3);
	      ThighBottom.setRotationPoint(-2.5F, 11.5F, -2.5F);
	      ThighBottom.setTextureSize(256, 256);
	      ThighBottom.mirror = true;
	      setRotation(ThighBottom, 0F, 0F, 0F);
	      Boot1 = new ModelRenderer(this, 88, 41);
	      Boot1.addBox(0F, 0F, 0F, 3, 8, 3);
	      Boot1.setRotationPoint(-3.5F, 17F, -2.5F);
	      Boot1.setTextureSize(256, 256);
	      Boot1.mirror = true;
	      setRotation(Boot1, 0F, 0F, 0F);
	      Toe1 = new ModelRenderer(this, 126, 24);
	      Toe1.addBox(0F, 0F, 0F, 2, 1, 1);
	      Toe1.setRotationPoint(-3F, 23F, -3F);
	      Toe1.setTextureSize(256, 256);
	      Toe1.mirror = true;
	      setRotation(Toe1, 0F, 0F, 0F);
	      Leg1 = new ModelRenderer(this, 117, 39);
	      Leg1.addBox(0F, 0F, 0F, 2, 5, 2);
	      Leg1.setRotationPoint(-3F, 12F, -2F);
	      Leg1.setTextureSize(256, 256);
	      Leg1.mirror = true;
	      setRotation(Leg1, 0F, 0F, 0F);
	      Diamond2 = new ModelRenderer(this, 82, 6);
	      Diamond2.addBox(0F, 0F, 0F, 1, 1, 1);
	      Diamond2.setRotationPoint(-2.7F, 16.3F, -2.3F);
	      Diamond2.setTextureSize(256, 256);
	      Diamond2.mirror = true;
	      setRotation(Diamond2, 0F, 0F, -0.7853982F);
	      Leg2 = new ModelRenderer(this, 117, 39);
	      Leg2.addBox(0F, 0F, 0F, 2, 5, 2);
	      Leg2.setRotationPoint(1F, 12F, -2F);
	      Leg2.setTextureSize(256, 256);
	      Leg2.mirror = true;
	      setRotation(Leg2, 0F, 0F, 0F);
	      Diamond3 = new ModelRenderer(this, 82, 6);
	      Diamond3.addBox(0F, 0F, 0F, 1, 1, 1);
	      Diamond3.setRotationPoint(1.3F, 16.3F, -2.3F);
	      Diamond3.setTextureSize(256, 256);
	      Diamond3.mirror = true;
	      setRotation(Diamond3, 0F, 0F, -0.7853982F);
	      Boot2 = new ModelRenderer(this, 88, 41);
	      Boot2.addBox(0F, 0F, 0F, 3, 8, 3);
	      Boot2.setRotationPoint(0.5F, 17F, -2.5F);
	      Boot2.setTextureSize(256, 256);
	      Boot2.mirror = true;
	      setRotation(Boot2, 0F, 0F, 0F);
	      Toe2 = new ModelRenderer(this, 126, 24);
	      Toe2.addBox(0F, 0F, 0F, 2, 1, 1);
	      Toe2.setRotationPoint(1F, 23F, -3F);
	      Toe2.setTextureSize(256, 256);
	      Toe2.mirror = true;
	      setRotation(Toe2, 0F, 0F, 0F);
	      Glove1 = new ModelRenderer(this, 134, 31);
	      Glove1.addBox(0F, 0F, 0F, 3, 5, 3);
	      Glove1.setRotationPoint(-6.5F, 11F, -2.5F);
	      Glove1.setTextureSize(256, 256);
	      Glove1.mirror = true;
	      setRotation(Glove1, 0F, 0F, 0F);
	      Glove2 = new ModelRenderer(this, 134, 31);
	      Glove2.addBox(0F, 0F, 0F, 3, 5, 3);
	      Glove2.setRotationPoint(3.5F, 11F, -2.5F);
	      Glove2.setTextureSize(256, 256);
	      Glove2.mirror = true;
	      setRotation(Glove2, 0F, 0F, 0F);
	      Arm2 = new ModelRenderer(this, 5, 3);
	      Arm2.addBox(0F, 0F, 0F, 2, 7, 2);
	      Arm2.setRotationPoint(3F, 4.9F, -2F);
	      Arm2.setTextureSize(256, 256);
	      Arm2.mirror = true;
	      setRotation(Arm2, 0F, 0F, -0.1396263F);
	      ShoulderCover2 = new ModelRenderer(this, 126, 5);
	      ShoulderCover2.addBox(0F, 0F, 0F, 2, 1, 3);
	      ShoulderCover2.setRotationPoint(2F, 4F, -2.5F);
	      ShoulderCover2.setTextureSize(256, 256);
	      ShoulderCover2.mirror = true;
	      setRotation(ShoulderCover2, 0F, 0F, 0F);
	  }
	  
	  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	  {
	    super.render(entity, f, f1, f2, f3, f4, f5);
	    setRotationAngles(f, f1, f2, f3, f4, f5);
	    Head.render(f5);
	    GlassesBottom1.render(f5);
	    GlassesTop.render(f5);
	    GlassesBottom2.render(f5);
	    Eye1.render(f5);
	    Pupil1.render(f5);
	    Neck.render(f5);
	    GemTop.render(f5);
	    GemBottom.render(f5);
	    Eye2.render(f5);
	    Pupil2.render(f5);
	    Torso.render(f5);
	    Diamond1.render(f5);
	    TorsoBottom.render(f5);
	    Waist.render(f5);
	    Hair.render(f5);
	    Arm1.render(f5);
	    ThighTop.render(f5);
	    ShoulderCover1.render(f5);
	    ThighBottom.render(f5);
	    Boot1.render(f5);
	    Toe1.render(f5);
	    Leg1.render(f5);
	    Diamond2.render(f5);
	    Leg2.render(f5);
	    Diamond3.render(f5);
	    Boot2.render(f5);
	    Toe2.render(f5);
	    Glove1.render(f5);
	    Glove2.render(f5);
	    Arm2.render(f5);
	    ShoulderCover2.render(f5);
	  }
	  
	  private void setRotation(ModelRenderer model, float x, float y, float z)
	  {
	    model.rotateAngleX = x;
	    model.rotateAngleY = y;
	    model.rotateAngleZ = z;
	  }
	  
	  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	  {
	    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
	  }

	}
